server:
  port: 8087
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    username: /tmall
    password: 123456
    virtual-host: /tmall
  redis:
    host: 192.168.53.128
    password: 12345678
tmall:
  sms:
    accessKeyId: LTAI4Fcv8xYMF3cj3c1p8UND  # 你自己的accessKeyId
    accessKeySecret: z9jrz7QtJabFKQ9na0prBEM02ffRAE  # 你自己的AccessKeySecret
    signName: CarryWang工作室   # 签名名称
    verifyCodeTemplate: SMS_184830127  # 模板名称
tencent:
  sms:
    secretId: AKIDc0CG5eP1qXnohMe0GH1VjiQt8mEQEPM4  # 你自己的secretId
    secretKey: cp55rOeeNt9nDMxJRIuFKDp67OTIsBXc # 你自己的secretKey
    appid: 1400325960 #应用id
    sign: CarryWang工作室  # 签名名称
    templateID: 547326 # 模板名称